name: "Template Repository Rename"
description: ""
branding:
  icon: "copy"
  color: "white"
inputs:
  from-name:
    description: "Original project name from the template repository"
  to-name:
    description: "New project name of the repository created"
  ignore-paths:
    description: "Paths to ignore"
  commit-message:
    description: "Commit message"
    default: "renamed"
  pr-branch-prefix:
    description: "PR branch prefix"
    default: "template-sync/"
  github-token:
    description: "GitHub token"
    default: ${{ github.token }}
  dry-run:
    description: "Dry run or not"
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
